---
title: "Equipe"
---

**Carlos Almada** é compositor, mestre e doutor em Música, sendo atualmente Professor Associado da Escola de Música da UFRJ e membro permanente do Programa de Pós-Graduação em Música da mesma instituição, no qual coordena projeto de pesquisa sobre estudos sistemáticos em música popular. É autor dos livros Arranjo (Editora da Unicamp, 2001), A estrutura do choro (Da Fonseca, 2006), Harmonia funcional (Editora da Unicamp, 2009), Contraponto em música popular (Editora da UFRJ, 2013), Nas fronteiras da tonalidade (Prisma, 2016), A harmonia de Jobim (Editora da Unicamp,  2022), A melodia de Jobim (Editora da Unicamp, 2023), Musical Variation: Toward a Transformational Perspective (Springer, 2023), Funcionalidade harmônica em música popular (Editora da Unicamp, 2025) e Redescobrindo Jobim (Editora da Unicamp, no prelo), tendo também publicado inúmeros artigos em periódicos e anais de congressos nacionais e internacionais. Almada é membro da Associação Brasileira de Teoria e Análise Musical, líder do grupo de pesquisa [MusMat](https://musmat.org/) e coordenador do [Projeto MPB](https://projetompb.com.br/).

**Hugo Carvalho** é natural de São Paulo (1989) e reside no Rio de Janeiro desde 2004. É formado em Matemática Aplicada pela UFRJ (2011), com Mestrado em Matemática Aplicada pela mesma instituição (2013) e Doutorado em Engenharia Elétrica, na área de Processamento de Sinais, também pela UFRJ (2017), orientado por Luiz Wagner Pereira Biscainho e Flávio Rainho Ávila. Aprendeu violão clássico aos 8 anos de idade, período em que morou no Paraguai, desenvolvendo desde então um grande interesse pela música latino-americana. Desde 2020, integra o Grupo de Pesquisa [MusMat](https://musmat.org/) e desde 2024 coordena o [Projeto MPB](https://projetompb.com.br/) juntamente com Carlos Almada Atualmente é professor adjunto do Departamento de Métodos Estatísticos da UFRJ, e membro do corpo editorial do periódico MusMat: Brazilian Journal of Music and Mathematics. Dedica-se também ao estudo de composição musical e ao violão clássico.

**Mario Adnet** compositor, arranjador, violonista e produtor carioca, tem se revezado entre entre sua produção pessoal e um mergulho profundo nas obras de autores-chave da música nacional como Villa-Lobos, Tom Jobim, Moacir Santos, Dorival Caymmi, Baden Powell e Luiz Eça. Adnet é vencedor de oito Prêmios da Música Brasileira, Ganhou duas vezes o Grammy Latino, em 2021, como produtor do single Talvez, de Caetano Veloso, na categoria Gravação do Ano, e em 2004, com Paulo Jobim, por Jobim Sinfônico, também indicado ao Grammy Americano em 2005 na categoria Crossover. Mario Adnet recebeu ainda 6 indicações ao Grammy Latino: Jobim Jazz ao Vivo (na categoria de melhor album de jazz latino em 2016), Dorival Caymmi Centenário, com Dori Caymmi (nas categorias de produtores do ano e melhor disco de MPB em 2015), Um Olhar Sobre Villa-Lobos (nas categorias de melhor album de música clássica e produtor, em 2013) e Choros & Alegria – Moacir Santos, com Zé Nogueira (na categoria de melhor álbum instrumental em 2006). Em 2025 recebeu o título de Notório Saber , equivalente ao título de doutor, da Universidade Federal do Rio de Janeiro.

**Rafael Bezerra** é compositor, arranjador, professor e produtor musical. É Doutor e Mestre em Composição Musical pela Universidade Federal do Estado do Rio de Janeiro (UNIRIO) e Bacharel na mesma área pela Escola de Música da Universidade Federal do Rio de Janeiro (EM-UFRJ). Possui especializações em Música para Cinema e Televisão, e em Educação Musical, ambas pelo Conservatório Brasileiro de Música (CBM - Centro Universitário). Na mesma instituição se formou em Licenciatura em Música. Cursou Regência Coral nos Seminários de Música Pró-Arte. Exerceu a função de professor em diversas instituições no Rio de Janeiro, como na Secretaria Municipal de Educação, Colégio Pedro II, Conservatório Brasileiro de Música (graduação e curso técnico), Academia de Música Lorenzo Fernandez e UNIRIO. Desde 2018, é professor universitário no curso de licenciatura em música da Universidade Católica de Petrópolis (UCP). O fascínio de Rafael pela música teve início no colégio, acompanhado pelos primeiros acordes no violão, e perdurou ao longo de toda a sua vida. Além de frequentar a Escola Portátil de Música e outros locais de estudo de música popular, atuou como regente e arranjador de corais e grupos instrumentais em diversas instituições. Dedicou-se também à produção de arranjos, composições e trilhas sonoras inspiradas na música popular brasileira. Desde 2014, envolve-se em pesquisas relacionadas ao tema, desenvolvidas na UFRJ, UNIRIO e UCP. Dentre essas pesquisas, destacam-se sua dissertação, na qual compôs a partir da análise de canções de Guinga, e sua tese, na qual, após examinar composições de Tim Rescala, criou texto, libreto e música para uma obra cênico-musical com sólida conexão com a cultura e a música popular brasileiras.

**Pedro Emmanuel Zisels** é músico, compositor e pesquisador de música popular do Brasil, com foco nos gêneros urbanos do choro e samba carioca. Desenvolve estudos sobre padrões de recorrência em domínios estruturais melódicos e harmônicos. Cursou Mestrado em Música (Composição) pela UFRJ, quando investigou padrões composicionais em contracantos de Pixinguinha, sendo orientado pelo prof. Dr. Carlos Almada, com coorientação de Pauxy Gentil-Nunes. Atualmente cursa o doutorado na linha Poéticas da Criação Musical na UFRJ, explorando modelos teóricos elaborados especificamente para a descrição e análise de melodias de samba carioca, com orientação do prof. Dr. Carlos Almada. É membro do grupo de Pesquisa [MusMat](https://musmat.org/) e integra a equipe de pesquisadores do [Projeto MPB](https://projetompb.com.br/).

**Max Kühn** é carioca, compositor e pesquisador. Atualmente é professor de Harmonia Funcional no Departamento de Composição da Escola de Música da Universidade Federal do Rio de Janeiro (UFRJ), instituição na qual concluiu o bacharelado em Composição, sob orientação de Liduino Pitombeira. É mestre em Música, na área de Processos Criativos, pelo Programa de Pós-Graduação em Música da UFRJ (PPGM-UFRJ), onde defendeu sua dissertação intitulada *Arquétipos de Voice Leadings na harmonia de Antônio Carlos Jobim: uma abordagem através da teoria das classes de condução de vozes parcimoniosas* sob orientação de Carlos Almada, com quem atualmente desenvolve sua pesquisa de doutorado. É autor de trabalhos publicados em periódicos científicos e anais de eventos acadêmicos. Sua pesquisa de doutorado investiga a harmonia musical e sua aplicação em processos criativos, com ênfase na investigação de modelos teóricos voltados à compreensão, sistematização e expansão das possibilidades composicionais contemporâneas.

**Tiê Kühl** é um campineiro bossa nova de vinte e dois anos (n. 2004). É apaixonado por aves brasileiras, pela natureza e principalmente pelo bioma da Mata Atlântica. Começou seus estudos musicais aos 2 anos de idade com a educadora musical e cantora lírica Agnes Moço, em Niterói, e, simultaneamente, iniciou o estudo do violino com Suray Soren e, posteriormente, aperfeiçoou os estudos com diversos professores, entre eles Paulo Bosisio, Karolin Broosch e Tiago Cosmo. Integrou o prestigioso Coral Infantil da UFRJ, sob regência e direção artística de Maria José Chevitarese, por 9 anos (2011-2020), e atualmente integra o Coral Brasil Ensemble-UFRJ. Atualmente (2026), cursa o bacharelado em regência orquestral, sob orientação do professor e maestro André Cardoso, pela Universidade Federal do Rio de Janeiro (UFRJ). Como compositor, teve aulas com Carlos Almada, Pauxy Gentil Nunes, Yahn Wagner e Liduino Pitombeira. Venceu a primeira edição do concurso de composição "Novos Sons Brasileiros" da orquestra São Paulo Chamber Soloists em 2025, com a Suíte Ibirapuera, estreada no Teatro Cultura Artística, em São Paulo. Suas influências musicais são ecléticas, tendo como triunvirato Antonio Carlos Jobim, Heitor Villa-Lobos e Maurice Ravel.

**Matheus Xavier Forli**, músico carioca nascido em 1980, teve sua primeira experiência com a performance musical em 1992, aos doze anos de idade, no Circo Voador/RJ, onde, na bateria, se apresentou com uma banda cover de rock nacional. A bateria é seu principal instrumento, tendo o violão e o piano como companheiros harmônicos e melódicos, aliados em suas composições. Músicas de Tom Jobim, Egberto Gismonti, Naná Vasconcelos, Gilberto Gil, Hermeto Pascoal, Joyce Moreno, Milton Nascimento, Elomar, Xangai, Antônio Nóbrega e muitos outros artistas da música brasileira sempre estiveram presentes em sua infância, pois faziam parte do gosto musical de seus pais. Com mais de 30 anos de experiência em performance musical, vem atuando em casas de show, bares, teatros, hotéis e festivais de música pelo Brasil, ao lado de artistas populares de diferentes gêneros. Atualmente, faz parte do quinteto musical Trem Mineiro Uai, com repertório exclusivamente mineiro; acompanha a cantora Fátima Regina no projeto Minha Praia é Bossa; é integrante da banda Alchemy; e está iniciando um projeto autoral chamado Tambores e Sensações. Em 2023, iniciou sua aventura no mundo acadêmico e cursa, atualmente, o oitavo período da graduação em Licenciatura em Música pela UFRJ. Seu interesse pelos estudos formais sempre o acompanhou, tendo estudado com os bateristas Fernando Pereira, Xande Figueiredo, Cristiano Galvão, Alex Buck e Felipe Continentino. Em 1994, estudou na Escola de Música Villa-Lobos (RJ) e, entre 2012 e 2014, cursou a Escola Portátil de Choro, na UNIRIO, ampliando suas experiências e seu contato com esse gênero musical. Não poderia deixar de citar os cinco anos vividos com Bernardo Ramos em um laboratório musical na Pro-Arte, período em que pôde absorver, na prática, uma experiência única, explorando novas possibilidades no modo de sentir e pensar a música. Atualmente, na UFRJ, tem o privilégio de participar, por indicação do professor Carlos Almada, de uma pesquisa de iniciação científica (bolsa PIBIC), intitulada Projeto MPB (projetompb.com.br), além de atuar como extensionista no Projeto Jobim 2027, em comemoração aos 100 anos de seu nascimento. Paralelamente à sua atuação como músico, projeta sua trajetória futura como professor de música, entendendo a docência como espaço de troca, escuta e construção coletiva do conhecimento. Seu interesse pedagógico articula prática instrumental, criação musical e reflexão crítica, compreendendo o ensino como continuidade de sua experiência artística.