---
title: "Sobre"
---

O projeto de extensão **2027, Ano Jobim**, vinculado à Escola de Mùsica da Universidade Federal do Rio de Janeiro, é destinado à divulgação pública geral, consistindo em um ciclo com 15 a 20 apresentações (que serão realizadas em frequência quinzenal, ao longo de 10 meses, entre março e dezembro de 2027), envolvendo diversos convidados e tipos de eventos, como palestras, mesas redondas e recitais musicais, tendo como elemento central a vida e a obra de Antonio Carlos Jobim.

A iniciativa visa homenagear o nosso maior compositor da música popular por ocasião das celebrações de seu centenário de nascimento, que acontecerá em 2027.  A ação se apresenta como uma proposta original e relevante, trazendo para as comunidades acadêmica e externa discussões e exposições relacionadas à extraordinária trajetória (humana e artística) de Jobim, bem como inúmeros tópicos de grande relevância teórico-musical, oriundos de aprofundadas pesquisas realizadas recentemente no âmbito do Programa de Pós-Graduação em Música desta universidade (PPGM-UFRJ), num arco temporal de cerca de 10 anos, pesquisa que  resultou em consideráveis produções bibliográfica e artística.

**Objetivos**

1.  Homenagear Jobim em seu centenário de nascimento;

2.	Apresentar à comunidade extensionista interna e externa aspectos diversos da multifacetada e rica obra jobiniana, por intermédio de uma série de eventos ao longo do ano de 2027

3.	Divulgar à comunidade extensionista interna e externa os principais elementos e resultados de uma sequência de projetos de pesquisa desenvolvidos no âmbito do Programa de Pós-Graduação em Música da UFRJ de 2017 à data presente, nos quais a música de Jobim ocupa espaço central;

4.	Conectar, através de discussões, rodas de debates, visões e abordagens distintas e complementares sobre a música e a vida de Jobim, a partir das esferas de atuação dos participantes convidados (musical, familiar, jornalística e acadêmica);

5.	Difundir os eventos através de plataformas de *streaming*, considerando ainda a possibilidade de publicações de resumos de palestras proferidas;

6.	Viabilizar uma chamada de composições originais baseadas em aspectos teóricos, estéticos ou analíticos da obra jobiniana, a serem interpretadas pelos grupos musicais estáveis da Escola de Música (UFRJazz, Quinteto Experimental de Sopros, Camerata de Cordas e Quarteto de Saxofones), bem como, eventualmente, por outras formações instrumentais, envolvendo alunos e professores da Escola.

**Equipe**

A ação contará com a participação direta de uma [equipe](equipe.qmd) multifacetada, envolvendo os corpos docente e discente: Carlos Almada (coordenador, professor, Escola de Música/UFRJ), Hugo Carvalho (professor, Instituto de Matemática/UFRJ), Mario Adnet (compositor, arranjador e produtor, recém laureado com o título de Doutor por Notório Saber em Música pela UFRJ), Rafael Bezerra (professor, Instituto Villa-Lobos/Unirio e Universidade Católica de Petrópolis), Pedro Zisels (doutorando, Escola de Música/UFRJ), Max Kühn (doutorando, Escola de Música/UFRJ), Tiê Kuhl (graduando em Regência, Escola de Música/UFRJ) e Matheus Xavier Forlí (graduando em Licenciatura, Escola de Música/UFRJ).